/**
 * SAST-Scan Rule Definitions
 * Each rule has: id, category, severity, pattern, message, fix, cwe, language
 */

export const SEVERITY = {
  CRITICAL: "critical",
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low",
  INFO: "info",
};

export const CATEGORY = {
  INJECTION: "Injection",
  XSS: "Cross-Site Scripting",
  CRYPTO: "Cryptography",
  AUTH: "Authentication & Secrets",
  MEMORY: "Memory Safety",
  PATH_TRAVERSAL: "Path Traversal",
  REDIRECT: "Open Redirect",
  INFO_DISCLOSURE: "Information Disclosure",
  DESERIALIZATION: "Deserialization",
  COMMAND_INJECTION: "Command Injection",
  INSECURE_DEPS: "Insecure Dependencies",
  STORAGE: "Insecure Storage",
  NETWORK: "Network Security",
  CODE_QUALITY: "Code Quality",
  PROTOTYPE_POLLUTION: "Prototype Pollution",
};

/**
 * Rules are de-duplicated and organized by category/severity.
 * Each rule is tested once per line.
 */
export const rules = [
  // ─── INJECTION ────────────────────────────────────────────────
  {
    id: "SAST-001",
    category: CATEGORY.INJECTION,
    severity: SEVERITY.CRITICAL,
    pattern: /eval\s*\(/,
    message: "Use of eval() allows arbitrary code execution",
    fix: "Replace eval() with JSON.parse() for JSON, or refactor to eliminate dynamic code execution entirely.",
    cwe: "CWE-95",
    language: "javascript",
  },
  {
    id: "SAST-002",
    category: CATEGORY.INJECTION,
    severity: SEVERITY.CRITICAL,
    pattern: /new\s+Function\s*\(/,
    message: "Dynamic code execution via new Function() constructor",
    fix: "Avoid new Function(). Use static function definitions or pre-approved function maps.",
    cwe: "CWE-95",
    language: "javascript",
  },
  {
    id: "SAST-003",
    category: CATEGORY.INJECTION,
    severity: SEVERITY.CRITICAL,
    pattern: /SELECT\s+[\w*,\s]+\s+FROM\s+\w+\s+WHERE\s+\w+\s*=\s*['"`+]/i,
    message: "Potential SQL Injection via string concatenation in query",
    fix: "Use parameterized queries or prepared statements (e.g., knex, pg, mysql2 with placeholders).",
    cwe: "CWE-89",
    language: "javascript",
  },
  {
    id: "SAST-004",
    category: CATEGORY.COMMAND_INJECTION,
    severity: SEVERITY.CRITICAL,
    pattern: /child_process\.(exec|execSync)\s*\(/,
    message: "Command injection risk via child_process.exec/execSync",
    fix: "Use child_process.execFile() or spawn() with a fixed command and validated arguments array.",
    cwe: "CWE-78",
    language: "javascript",
  },

  // ─── XSS ──────────────────────────────────────────────────────
  {
    id: "SAST-010",
    category: CATEGORY.XSS,
    severity: SEVERITY.HIGH,
    pattern: /\.innerHTML\s*=\s*(?!['"`]<)/,
    message: "Directly assigning untrusted data to innerHTML risks XSS",
    fix: "Use textContent for plain text, or sanitize HTML with DOMPurify before assigning to innerHTML.",
    cwe: "CWE-79",
    language: "javascript",
  },
  {
    id: "SAST-011",
    category: CATEGORY.XSS,
    severity: SEVERITY.HIGH,
    pattern: /document\.write\s*\(/,
    message: "document.write() can introduce XSS vulnerabilities",
    fix: "Use DOM manipulation methods (createElement, appendChild) instead of document.write().",
    cwe: "CWE-79",
    language: "javascript",
  },
  {
    id: "SAST-012",
    category: CATEGORY.XSS,
    severity: SEVERITY.HIGH,
    pattern: /innerHTML\s*=\s*document\.cookie/,
    message: "Writing cookie data directly to innerHTML exposes XSS attack surface",
    fix: "Never render cookie values in the DOM. Use server-side rendering or sanitize with DOMPurify.",
    cwe: "CWE-79",
    language: "javascript",
  },
  {
    id: "SAST-013",
    category: CATEGORY.XSS,
    severity: SEVERITY.MEDIUM,
    pattern: /dangerouslySetInnerHTML\s*=\s*\{\s*\{/,
    message: "React dangerouslySetInnerHTML usage may introduce XSS",
    fix: "Sanitize HTML content with DOMPurify before passing to dangerouslySetInnerHTML.",
    cwe: "CWE-79",
    language: "javascript",
  },

  // ─── CRYPTOGRAPHY ─────────────────────────────────────────────
  {
    id: "SAST-020",
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.HIGH,
    pattern: /crypto\.createHash\s*\(\s*['"`]md5['"`]\s*\)/i,
    message: "MD5 is a cryptographically broken hash function",
    fix: "Use bcrypt, Argon2, or scrypt for passwords. Use SHA-256+ for non-password hashing.",
    cwe: "CWE-327",
    language: "javascript",
  },
  {
    id: "SAST-021",
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.HIGH,
    pattern: /crypto\.createHash\s*\(\s*['"`]sha1['"`]\s*\)/i,
    message: "SHA-1 is deprecated and collision-vulnerable",
    fix: "Use SHA-256 or stronger (crypto.createHash('sha256')) for general hashing.",
    cwe: "CWE-327",
    language: "javascript",
  },
  {
    id: "SAST-022",
    category: CATEGORY.CRYPTO,
    severity: SEVERITY.MEDIUM,
    pattern: /Math\.random\s*\(\s*\)/,
    message: "Math.random() is not cryptographically secure",
    fix: "Use crypto.getRandomValues() (browser) or crypto.randomBytes() (Node.js) for security-sensitive randomness.",
    cwe: "CWE-338",
    language: "javascript",
  },

  // ─── AUTHENTICATION & SECRETS ─────────────────────────────────
  {
    id: "SAST-030",
    category: CATEGORY.AUTH,
    severity: SEVERITY.CRITICAL,
    pattern: /const\s+(password|passwd|pwd|secret|api_?key|auth_?token|private_?key)\s*=\s*['"`][^'"` ]{3,}['"`]/i,
    message: "Hardcoded credential or secret detected in source code",
    fix: "Store secrets in environment variables and access via process.env. Use a secrets manager in production.",
    cwe: "CWE-798",
    language: "javascript",
  },
  {
    id: "SAST-031",
    category: CATEGORY.AUTH,
    severity: SEVERITY.HIGH,
    pattern: /jwt\.sign\s*\(.*,\s*['"`](?:secret|password|test|dev|key)['"`]/i,
    message: "Weak or predictable JWT signing secret",
    fix: "Use a cryptographically random secret of at least 256 bits. Store it in environment variables.",
    cwe: "CWE-321",
    language: "javascript",
  },
  {
    id: "SAST-032",
    category: CATEGORY.AUTH,
    severity: SEVERITY.HIGH,
    pattern: /jwt\.verify\s*\(.*algorithm.*none/i,
    message: "JWT 'none' algorithm bypasses signature verification",
    fix: "Always specify and enforce a strong algorithm (e.g., RS256, HS256). Reject tokens with 'none' algorithm.",
    cwe: "CWE-347",
    language: "javascript",
  },

  // ─── MEMORY SAFETY ────────────────────────────────────────────
  {
    id: "SAST-040",
    category: CATEGORY.MEMORY,
    severity: SEVERITY.MEDIUM,
    pattern: /new\s+Buffer\s*\(/,
    message: "Deprecated Buffer() constructor is unsafe and can expose memory",
    fix: "Use Buffer.from(), Buffer.alloc(), or Buffer.allocUnsafe() depending on your use case.",
    cwe: "CWE-119",
    language: "javascript",
  },
  {
    id: "SAST-041",
    category: CATEGORY.MEMORY,
    severity: SEVERITY.LOW,
    pattern: /setInterval\s*\(.*=>\s*\{[^}]*\.push\s*\(/,
    message: "Unbounded array growth inside setInterval may cause memory leak",
    fix: "Cap the array size, clear the interval when done, or use a circular buffer.",
    cwe: "CWE-400",
    language: "javascript",
  },

  // ─── PATH TRAVERSAL ───────────────────────────────────────────
  {
    id: "SAST-050",
    category: CATEGORY.PATH_TRAVERSAL,
    severity: SEVERITY.HIGH,
    pattern: /path\.join\s*\([^)]*(?:req\.|input|params|query|body)/,
    message: "User-controlled input in path.join() may allow path traversal",
    fix: "Validate and sanitize file paths. Use path.resolve() + check that result starts within allowed base directory.",
    cwe: "CWE-22",
    language: "javascript",
  },
  {
    id: "SAST-051",
    category: CATEGORY.PATH_TRAVERSAL,
    severity: SEVERITY.HIGH,
    pattern: /fs\.(readFile|writeFile|readFileSync|writeFileSync)\s*\([^)]*(?:req\.|input|params|query|body)/,
    message: "User-controlled input passed to fs file operations risks path traversal",
    fix: "Validate paths against an allowlist and ensure they resolve within the intended directory.",
    cwe: "CWE-22",
    language: "javascript",
  },

  // ─── OPEN REDIRECT ────────────────────────────────────────────
  {
    id: "SAST-060",
    category: CATEGORY.REDIRECT,
    severity: SEVERITY.MEDIUM,
    pattern: /res\.redirect\s*\([^)]*(?:req\.|input|params|query|body)/,
    message: "User-controlled redirect destination may enable open redirect attacks",
    fix: "Validate redirect URLs against an allowlist of trusted domains before redirecting.",
    cwe: "CWE-601",
    language: "javascript",
  },
  {
    id: "SAST-061",
    category: CATEGORY.REDIRECT,
    severity: SEVERITY.MEDIUM,
    pattern: /window\.location\s*(?:\.href)?\s*=\s*(?!['"`]https?:\/\/(?:localhost|your-domain))/,
    message: "Potentially unvalidated URL assignment to window.location",
    fix: "Validate the URL against an allowlist before assigning to window.location.",
    cwe: "CWE-601",
    language: "javascript",
  },

  // ─── INFORMATION DISCLOSURE ───────────────────────────────────
  {
    id: "SAST-070",
    category: CATEGORY.INFO_DISCLOSURE,
    severity: SEVERITY.MEDIUM,
    pattern: /res\.(?:send|json)\s*\(\s*(?:err|error)\s*(?:\.|\.message)?\s*\)/,
    message: "Sending raw error objects to clients may expose stack traces or internals",
    fix: "Log errors server-side and send only a generic error message to the client.",
    cwe: "CWE-209",
    language: "javascript",
  },
  {
    id: "SAST-071",
    category: CATEGORY.INFO_DISCLOSURE,
    severity: SEVERITY.HIGH,
    pattern: /res\.json\s*\(\s*\{[^}]*password[^}]*\}\s*\)/i,
    message: "Password field may be included in API response",
    fix: "Explicitly exclude sensitive fields (password, token, secret) before sending API responses.",
    cwe: "CWE-312",
    language: "javascript",
  },
  {
    id: "SAST-072",
    category: CATEGORY.INFO_DISCLOSURE,
    severity: SEVERITY.LOW,
    pattern: /console\.log\s*\([^)]*(?:password|secret|token|key|auth)/i,
    message: "Sensitive data may be logged to console",
    fix: "Remove or mask sensitive data before logging. Use a structured logger with redaction support.",
    cwe: "CWE-532",
    language: "javascript",
  },

  // ─── NETWORK SECURITY ─────────────────────────────────────────
  {
    id: "SAST-080",
    category: CATEGORY.NETWORK,
    severity: SEVERITY.MEDIUM,
    pattern: /['"`]http:\/\/(?!localhost|127\.0\.0\.1)/,
    message: "Unencrypted HTTP URL detected for non-localhost endpoint",
    fix: "Use HTTPS for all external communications to prevent man-in-the-middle attacks.",
    cwe: "CWE-319",
    language: "javascript",
  },
  {
    id: "SAST-081",
    category: CATEGORY.NETWORK,
    severity: SEVERITY.LOW,
    pattern: /async\s+function[^{]*\{[^}]*await\s+fetch\s*\(/,
    message: "fetch() call without timeout may result in hanging requests",
    fix: "Wrap fetch() with AbortController and a timeout: const controller = new AbortController(); setTimeout(() => controller.abort(), 5000);",
    cwe: "CWE-400",
    language: "javascript",
  },
  {
    id: "SAST-082",
    category: CATEGORY.NETWORK,
    severity: SEVERITY.MEDIUM,
    pattern: /new\s+XMLHttpRequest\s*\(\s*\)/,
    message: "XMLHttpRequest used without CSRF protection considerations",
    fix: "Use the fetch API with appropriate CORS headers and CSRF tokens. Consider SameSite cookie attributes.",
    cwe: "CWE-352",
    language: "javascript",
  },

  // ─── INSECURE STORAGE ─────────────────────────────────────────
  {
    id: "SAST-090",
    category: CATEGORY.STORAGE,
    severity: SEVERITY.MEDIUM,
    pattern: /localStorage\.setItem\s*\(/,
    message: "Data stored in localStorage is accessible via JavaScript (XSS risk)",
    fix: "Avoid storing sensitive data (tokens, PII) in localStorage. Use HttpOnly cookies or server-side sessions.",
    cwe: "CWE-922",
    language: "javascript",
  },
  {
    id: "SAST-091",
    category: CATEGORY.STORAGE,
    severity: SEVERITY.MEDIUM,
    pattern: /sessionStorage\.setItem\s*\(/,
    message: "Data stored in sessionStorage is accessible via JavaScript (XSS risk)",
    fix: "Avoid storing sensitive data in sessionStorage. Use HttpOnly cookies or server-side sessions.",
    cwe: "CWE-922",
    language: "javascript",
  },
  {
    id: "SAST-092",
    category: CATEGORY.STORAGE,
    severity: SEVERITY.MEDIUM,
    pattern: /JSON\.parse\s*\(\s*localStorage\.getItem\s*\(/,
    message: "Parsing untrusted data from localStorage without validation",
    fix: "Validate and sanitize data retrieved from localStorage before parsing or using it.",
    cwe: "CWE-502",
    language: "javascript",
  },

  // ─── PROTOTYPE POLLUTION ──────────────────────────────────────
  {
    id: "SAST-100",
    category: CATEGORY.PROTOTYPE_POLLUTION,
    severity: SEVERITY.HIGH,
    pattern: /Object\.assign\s*\(\s*(?:target|\w+)\s*,\s*(?:source|req\.body|req\.query|input)/,
    message: "Object.assign with user-controlled source may enable prototype pollution",
    fix: "Use structured cloning (structuredClone), validate inputs, or use lodash's _.merge with care. Freeze prototypes in critical paths.",
    cwe: "CWE-1321",
    language: "javascript",
  },
  {
    id: "SAST-101",
    category: CATEGORY.PROTOTYPE_POLLUTION,
    severity: SEVERITY.HIGH,
    pattern: /\[\s*['"`]__proto__['"`]\s*\]|__proto__\s*:/,
    message: "Direct __proto__ manipulation detected - prototype pollution vector",
    fix: "Never allow user input to set __proto__, constructor, or prototype keys. Use Object.create(null) for safe data maps.",
    cwe: "CWE-1321",
    language: "javascript",
  },

  // ─── DESERIALIZATION ──────────────────────────────────────────
  {
    id: "SAST-110",
    category: CATEGORY.DESERIALIZATION,
    severity: SEVERITY.HIGH,
    pattern: /serialize-javascript|node-serialize|\.unserialize\s*\(/,
    message: "Insecure deserialization library or pattern detected",
    fix: "Use JSON.parse() for data interchange. If you need serialization, use a safe library and validate schemas.",
    cwe: "CWE-502",
    language: "javascript",
  },

  // ─── INSECURE DEPENDENCIES ────────────────────────────────────
  {
    id: "SAST-120",
    category: CATEGORY.INSECURE_DEPS,
    severity: SEVERITY.INFO,
    pattern: /require\s*\(\s*['"`]dotenv['"`]\s*\)\s*\.config\s*\(\s*\)/,
    message: "dotenv loaded without environment validation",
    fix: "Validate required environment variables at startup using a schema validator (e.g., envalid, zod).",
    cwe: "CWE-15",
    language: "javascript",
  },

  // ─── CODE QUALITY ─────────────────────────────────────────────
  {
    id: "SAST-130",
    category: CATEGORY.CODE_QUALITY,
    severity: SEVERITY.LOW,
    pattern: /alert\s*\(/,
    message: "alert() usage can be exploited for UI redress or social engineering",
    fix: "Replace alert() with application-level notification UI components.",
    cwe: "CWE-116",
    language: "javascript",
  },
  {
    id: "SAST-131",
    category: CATEGORY.CODE_QUALITY,
    severity: SEVERITY.LOW,
    pattern: /fs\.readFileSync\s*\(/,
    message: "Synchronous file read blocks the event loop",
    fix: "Use async fs.readFile() with proper error handling, or fs.promises.readFile().",
    cwe: "CWE-400",
    language: "javascript",
  },
  {
    id: "SAST-132",
    category: CATEGORY.CODE_QUALITY,
    severity: SEVERITY.INFO,
    pattern: /TODO|FIXME|HACK|XXX/,
    message: "Unresolved code annotation found",
    fix: "Review and resolve TODO/FIXME/HACK annotations before production deployment.",
    cwe: null,
    language: "javascript",
  },
];

export default rules;